version: '3.8'

services:
  mycsharpproject:
    image: mycsharpproject
    build:
      context: .
      dockerfile: ./MyCSharpProject/Dockerfile
    container_name: mycsharpproject
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - Redis__Host=redis
      - Redis__Port=6380
      - Redis__Password=lekhanhtoan123
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - mycsharpproject-network

  redis:
    image: redis:alpine
    container_name: redis-db
    ports:
      - "6380:6380"
    environment:
      - REDIS_PASSWORD=lekhanhtoan123
    volumes:
      - redis-data:/data
    command: sh -c "apk add --no-cache bash && redis-server --requirepass lekhanhtoan123"
    networks:
      - mycsharpproject-network

networks:
  mycsharpproject-network:
    driver: bridge

volumes:
  redis-data: